
test:
	@python tournament_test.py
	@python tournament_rematch_tests.py

test-rematch:
	@python tournament_rematch_tests.py

test-basic:
	@python tournament_test.py

simulation:
	@python tournament_simulation.py
